#!/usr/bin/env bash

# https://stackoverflow.com/questions/56534678/how-to-create-a-cli-in-python-that-can-be-installed-with-pip

if [[ ! $@ ]]; then
    python3 -m dsv -h
else
    python3 -m dsv $@
fi